version: '3.5'

services:
  app:
    # image: lspeixotodev/igrejapentecostalreformada:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: igrejapentecostalreformada
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules