version: '3.5'

services:
  igrejapentecostalreformada-ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: lspeixotodev/igrejapentecostalreformada-ui
    container_name: igrejapentecostalreformada-ui
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules