export const financeParameters = {
  financeNoteCategories: [
    'Patrimônio',
    'Manutenção',
    'EBD',
    'Água e Luz',
    'Limpeza',
    'Ceia do Senhor',
    'Ação Social',
    'Doações',
    'Alimentação',
    'Prebenda',
    'Repasse',
    'Campanhas',
    'Biblioteca',
    'Outras Despesas',
    'Internet',
    'Contabilidade',
    'Jantinha',
    'Missões',
    'Decoração',
    'Impressões e MKT',
    'Mensalidade Seminário 1',
    'Mensalidade Seminário 2',
    'Mensalidade Seminário 3',
    'Mensalidade Seminário 4',
    'Dízimos',
    'Ofertas',
    'Campanhas',
    'Seminário',
  ],
  financePaymentVoucherOptions: ['Não se aplica', 'Pendente', 'Salvo'],
};
