export const registerParameters = {
  engagements: [1, 2, 3, 4, 5],
  baptismOption: ['Sim', 'Não'],
  communitiesOption: [
    'Nenhuma',
    'Assembléia de Deus',
    'Congregação Cristã no Brasil',
    'Católica Apostólica Romana',
    'Universal do Reino de Deus',
    'Evangelho Quadrangular',
    'Convenção Batista Brasileira',
    'Renascer em Cristo',
    'Adventista',
    'Internacional da Graça de Deus',
    'Pentecostal Deus é Amor',
    'Presbiteriana do Brasil',
    'Evangélica de Confissão Luterana no Brasil',
    'Batista',
    'Cristã Maranata',
    'Maná',
    'Mundial do Poder de Deus',
    'Metodista do Brasil',
    'Evangélica Luterana do Brasil',
    'Evangélica Pentecostal O Brasil Para Cristo',
    'Comunidade Evangélica Sara Nossa Terra',
    'Presbiteriana Renovada do Brasil',
    'Nazareno',
    'Casa da Bênção',
    'Metodista Wesleyana',
    'Presbiteriana Independente do Brasil',
    'Aliança das Igrejas Cristãs Nova Vida',
    'Avivamento Bíblico',
    'Adventista da Promessa',
    'Apostólica Fonte da Vida',
    'Batista da Lagoinha',
    'Associação das Igrejas Batistas Regulares do Brasil',
    'Igreja Unida',
    'Evangélica Congregacional do Brasil',
    'Cristã Evangélica',
    'Verbo da Vida',
    'Videira',
    'Igreja de Deus no Brasil',
    'Cristã Pentecostal da Bíblia do Brasil',
    'Metodista Livre',
    'Cristã Presbiteriana',
    'Presbiteriana Conservadora do Brasil',
    'Presbiteriana Unida do Brasil',
    'Presbiteriana Fundamentalista do Brasil',
    'Presbiteriana Coreana Americana',
    'Indígena Presbiteriana do Brasil',
    'Cristã da Aliança',
  ],
  craftOption: [
    'Diácono',
    'Pastor',
    'Presbítero',
    'Líder de Pequeno Grupo',
    'Professor',
    'Músico',
    'Irmão(ã)',
  ],
  interestsOption: ['Louvor', 'Ensino', 'Pregação', 'Limpeza', 'Ação Social', 'Cozinha', 'Outro'],
  maritalStatusOptions: ['Solteiro', 'Casado', 'Separado', 'Divorciado', 'Viúvo'],
  membershipOption: ['Membro Comungante', 'Membro Afastado'],
  schoolingOptions: [
    'Fundamental - Incompleto',
    'Fundamental - Completo',
    'Médio - Incompleto',
    'Médio - Completo',
    'Superior - Incompleto',
    'Superior - Completo',
    'Pós-graduação - Incompleto',
    'Pós-graduação - Completo',
  ],
  sexOptions: ['Masculino', 'Feminino'],
  stateOptions: [
    'AC',
    'AL',
    'AP',
    'AM',
    'BA',
    'CE',
    'DF',
    'ES',
    'GO',
    'MA',
    'MS',
    'MT',
    'MG',
    'PA',
    'PB',
    'PR',
    'PE',
    'PI',
    'RJ',
    'RN',
    'RS',
    'RO',
    'RR',
    'SC',
    'SP',
    'SE',
    'TO',
  ],
};
